[build-system]
requires = ["setuptools>=69", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "battinfoconverter-backend"
version = "3.3.0"
description = "Backend conversion module for BattInfoConverter"
readme = { file = "README.md", content-type = "text/markdown" }
requires-python = ">=3.10"
license = { text = "MIT" }
authors = [{ name = "Nukorn Plainpan", email = "econversion@empa.ch" }]

dependencies = [
  "pandas>=2,<3",
  "openpyxl>=3.1",
  "simplejson",
]

classifiers = [
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent",
  "Intended Audience :: Science/Research",
  "Topic :: Scientific/Engineering",
]

[project.urls]
Homepage = "https://github.com/EmpaEconversion/BattInfoConverter"
Repository = "https://github.com/EmpaEconversion/BattInfoConverter"

[tool.setuptools]
package-dir = { "" = "src" }

[tool.setuptools.packages.find]
where = ["src"]
include = ["battinfoconverter_backend*"]

[tool.setuptools.package-data]
"battinfoconverter_backend" = ["_context/*.json"]
"battinfoconverter_backend.templates" = ["*.json"]

[project.optional-dependencies]
app = [
  "streamlit>=1.50.0",
]
dev = [
  "pytest>=8.4.2",
  "ruff>=0.15.7",
  "pre-commit>=4.5.1",
  "pyld>=2.0.4",
  "pytest-cov>=7.1.0",
  "rdflib>=7.6.0",
  "requests>=2.32.5",
]

[tool.ruff]
line-length = 120
lint.select = ["ALL"]
lint.ignore = [
    "N803",
    "N806",
    "N815",
    "PLR2004",
    "TD002",
    "TD003",
    "D203",
    "D213",
    "COM812",
]
fix = true

[project.scripts]
battinfoconverter-template = "battinfoconverter_backend.templates.template_conversion:main"
